# Generated by Django 4.2.2 on 2023-07-26 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('f_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('f_id', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=100)),
                ('f_locality', models.CharField(max_length=100)),
                ('f_ac', models.FloatField()),
            ],
            options={
                'db_table': 'farmers',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('r_kg', models.FloatField()),
                ('r_deliverer', models.CharField(max_length=50)),
                ('r_f_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.farmers')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
    ]
