# Generated by Django 4.2.2 on 2023-07-26 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='r_received_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmers',
            name='f_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmers',
            name='f_photo',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='farmers',
            name='last_paid',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='f_ac',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='f_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='f_locality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='f_name',
            field=models.CharField(max_length=50),
        ),
    ]
