# Generated by Django 4.2.2 on 2023-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_delivery_r_received_by_farmers_f_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='f_ac',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='f_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='f_locality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='f_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='f_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
